FROM alpine:3.21

RUN apk add --no-cache \
    curl \
    qemu-system-arm \
    && rm -rf /var/cache/apk/* \
    && wget https://jenkins.openbmc.org/job/latest-master/label=docker-builder,target=romulus/lastSuccessfulBuild/artifact/openbmc/build/tmp/deploy/images/romulus/obmc-phosphor-image-romulus.static.mtd -O /obmc-phosphor-image-romulus.static.mtd

CMD ["qemu-system-arm", "-m 256 -M romulus-bmc -nographic \
    -drive file=/obmc-phosphor-image-romulus.static.mtd,format=raw,if=mtd \
    -net nic -net user,hostfwd=:127.0.0.1:2222-:22,hostfwd=:127.0.0.1:2443-:443,hostname=qemu"]