services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
      - "2443:2443"
      - "2223:2222"
      - "2624:2623"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
volumes:
  jenkins_home:
